### ISSUE TITLE
Error refreshing prompt

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/compare_with_wikidata#127]
I'm seeing the following error when trying to refresh a prompt on the current `master` (a55b0befe6f00bd5dfd46cb85837678a222ca88f).

```
TypeError: no implicit conversion of nil into String
  /Users/chris/Code/everypolitician/compare_with_wikidata/lib/compare_with_wikidata/diff_row/cell.rb:54:in `initialize'
  /Users/chris/Code/everypolitician/compare_with_wikidata/lib/compare_with_wikidata/diff_row/cell.rb:54:in `new'
  /Users/chris/Code/everypolitician/compare_with_wikidata/lib/compare_with_wikidata/diff_row/cell.rb:54:in `sparql_value'
  /Users/chris/Code/everypolitician/compare_with_wikidata/lib/compare_with_wikidata/diff_row/cell.rb:62:in `value'
  /Users/chris/Code/everypolitician/compare_with_wikidata/lib/compare_with_wikidata/diff_row/cell.rb:11:in `cell_values'
  /Users/chris/Code/everypolitician/compare_with_wikidata/lib/compare_with_wikidata/diff_row.rb:64:in `block in value_cells'
  /Users/chris/Code/everypolitician/compare_with_wikidata/lib/compare_with_wikidata/diff_row.rb:63:in `each'
  /Users/chris/Code/everypolitician/compare_with_wikidata/lib/compare_with_wikidata/diff_row.rb:63:in `flat_map'
  /Users/chris/Code/everypolitician/compare_with_wikidata/lib/compare_with_wikidata/diff_row.rb:63:in `value_cells'
  /Users/chris/Code/everypolitician/compare_with_wikidata/lib/compare_with_wikidata/diff_row.rb:19:in `template_params'
  (erb):10:in `block (2 levels) in run!'
  (erb):8:in `each'
  (erb):8:in `block in run!'
  /Users/chris/.rbenv/versions/2.5.0/lib/ruby/2.5.0/erb.rb:885:in `eval'
  /Users/chris/.rbenv/versions/2.5.0/lib/ruby/2.5.0/erb.rb:885:in `result'
  /Users/chris/Code/everypolitician/compare_with_wikidata/lib/compare_with_wikidata.rb:45:in `block in run!'
  /Users/chris/Code/everypolitician/compare_with_wikidata/lib/compare_with_wikidata.rb:42:in `each'
  /Users/chris/Code/everypolitician/compare_with_wikidata/lib/compare_with_wikidata.rb:42:in `run!'
  /Users/chris/Code/everypolitician/compare_with_wikidata/exe/compare_with_wikidata:22:in `<top (required)>'
  /Users/chris/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bin/compare_with_wikidata:23:in `load'
  /Users/chris/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bin/compare_with_wikidata:23:in `<top (required)>'
```

After a bit of investigation it seems that the error was introduced in #120 which added a `CellValue` class. Because this class inherits from `String` it expects a string to be passed to the constructor, but `nil` is actually being passed. Additionally it seems that casting that `nil` to a string still produces a slightly incorrect result:

```
Expected @@=->|start_date=|start_date_sparql=|start_date_csv=
Actual: @@=->|start_date=->|start_date_sparql=|start_date_csv=
```

**Comment by chrismytton** [comment]
This is the prompt I'm trying to refresh: https://www.wikidata.org/wiki/User:Chris_Mytton/sandbox/prompts/Pakistan_National_Assembly_EveryPolitician
